## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - PROVIDER-INFRA-SETUP
  - APP-FUNC-TEST
  - UPGRADE-OPENEBS
  - APP-CHAOS-TEST
  - CLUSTER-CLEANUP

variables:
  utils_path: "/builds/openebs/e2e-aws/script/utils"

## Setup the kubernetes cluster

aws-cluster:
  image: harshshekhar15/gitlab-job:v6
  stage: CLUSTER-SETUP 
  script: 
    - ./script/1-cluster-setup/aws
  artifacts:
    paths:
      - aws/

## Setup OpenEBS control plane

openebs-aws-deploy:
  image: harshshekhar15/gitlab-job:v6
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - aws-cluster
  script:
   - chmod 775 ./script/2-infra-setup/openebs-deploy/infra-setup
   - ./script/2-infra-setup/openebs-deploy/infra-setup
  artifacts:
    paths:
      - aws-openebs/

openebs-sc-deploy:
  image: harshshekhar15/gitlab-job:v6
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - aws-cluster
  script:
   - chmod 775 ./script/2-infra-setup/storage-policies/openebs-sc
   - ./script/2-infra-setup/storage-policies/openebs-sc
  artifacts:
    paths:
      - aws-openebs/

cStor-striped-pool:
  image: harshshekhar15/gitlab-job:v6
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - aws-cluster
  script:
   - chmod 775 ./script/2-infra-setup/create-striped-pool/create-striped-pool
   - ./script/2-infra-setup/create-striped-pool/create-striped-pool
  artifacts:
    paths:
      - aws-openebs/

cstor-operator-deploy:
  image: harshshekhar15/gitlab-job:v6
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - aws-cluster
  script:
   - chmod 775 ./script/2-infra-setup/cstor-cspc-operator/cspc-cstor-operator
   - ./script/2-infra-setup/cstor-cspc-operator/cspc-cstor-operator
  artifacts:
    paths:
      - aws-openebs/

csi-provisioner:
  image: harshshekhar15/gitlab-job:v6
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - aws-cluster
  script:
   - chmod 775 ./script/2-infra-setup/cstor-csi-provisioner/cstor-csi-provisioner
   - ./script/2-infra-setup/cstor-csi-provisioner/cstor-csi-provisioner
  artifacts:
    paths:
      - aws-openebs/            

# ## Define job template for func jobs    
.func_test_template:
  image: harshshekhar15/gitlab-job:v6
  stage: APP-FUNC-TEST
  dependencies:
    - openebs-aws-deploy
  artifacts:
    paths:
     - aws-openebs/

busybox-deployment-cstor:
  extends: .func_test_template
  script:
    - chmod 775 ./script/3-functional/busybox-deployment-cstor/busybox-deployment-cstor
    - ./script/3-functional/busybox-deployment-cstor/busybox-deployment-cstor

percona-deployment-cstor:
  extends: .func_test_template
  script:
    - chmod 775 ./script/3-functional/percona-deployment-cstor/percona-deployment-cstor
    - ./script/3-functional/percona-deployment-cstor/percona-deployment-cstor


.upgrade_openebs:
  image: harshshekhar15/gitlab-job:v6
  stage: UPGRADE-OPENEBS
  dependencies:
    - openebs-aws-deploy
  artifacts:
    paths:
     - aws-openebs/

upgrade-control-plane:
  extends: .upgrade_openebs
  script:
    - chmod 775 ./script/4-upgrade-openebs/upgrade-control-plane
    - ./script/4-upgrade-openebs/upgrade-control-plane

upgrade-cstor-operator:
  extends: .upgrade_openebs
  script:
    - chmod 775 ./script/4-upgrade-openebs/upgrade-cstor-operator
    - ./script/4-upgrade-openebs/upgrade-cstor-operator

upgrade-cspc-csi:
  extends: .upgrade_openebs
  script:
    - chmod 775 ./script/4-upgrade-openebs/upgrade-cstor-csi
    - ./script/4-upgrade-openebs/upgrade-cstor-csi

.chaos_test_template:
  image: harshshekhar15/gitlab-job:v6
  stage: APP-CHAOS-TEST
  dependencies:
    - openebs-aws-deploy
  artifacts:
    paths:
     - aws-openebs/
    
busybox-target-kill:
  extends: .chaos_test_template
  script:
    - chmod 775 ./script/5-chaos/bb-target-kill
    - ./script/5-chaos/bb-target-kill

busybox-deployment-target-network-delay:
  extends: .chaos_test_template
  script:
    - chmod 775 ./script/5-chaos/bb-deployment-target-nw-delay
    - ./script/5-chaos/bb-deployment-target-nw-delay

percona-target-network-delay:
  extends: .chaos_test_template
  script:
    - chmod 775 ./script/5-chaos/percona-target-nw-delay
    - ./script/5-chaos/percona-target-nw-delay

percona-cstor:
  extends: .chaos_test_template
  script:
    - chmod 775 ./script/5-chaos/percona-deployment-cstor
    - ./script/5-chaos/percona-deployment-cstor

## Deprrovision kubernets cluster

cleanup-aws:
  when: always
  image: harshshekhar15/gitlab-job:v6
  dependencies:
    - aws-cluster
  stage: CLUSTER-CLEANUP
  script: 
    - chmod 755 ./script/6-cleanup/aws-cleanup
    - ./script/6-cleanup/aws-cleanup
