stages:
  - cluster-setup
  - infra-setup
  - stateful-apps-deploy
  - apps-loadgen
  - chaos-test
  - cleanup
  - deploy

aws-cluster:
  image: atulabhi/kops:v8
  stage: cluster-setup
  script: 
    - chmod 755 ./script/aws
    - ./script/aws

  artifacts:
    paths:
      - aws/

openebs-aws-deploy:
  image: atulabhi/kops:v8
  stage: infra-setup
  dependencies:
    - aws-cluster
  script: 
   - echo "deploying OpenEBS on AWS"
   - chmod 775 ./script/infra-setup
   - ./script/infra-setup
  
  artifacts:
    paths:
      - aws-openebs/

percona-jiva:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-aws-deploy
  script: 
   #- echo "jobs-AWS-Started"
   - chmod 775 ./script/percona-app-deploy
   - ./script/percona-app-deploy

  artifacts:
    paths:
      - aws-openebs/

mongodb-jiva:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-aws-deploy
  script: 
   #- echo "jobs-AWS-Started"
   - chmod 775 ./script/mongodb-app-deploy
   - ./script/mongodb-app-deploy

  artifacts:
    paths:
      - aws-openebs/

postgres-jiva:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-aws-deploy
  script: 
   #- echo "jobs-AWS-Started"
   - chmod 775 ./script/postgres-app-deploy
   - ./script/postgres-app-deploy

  artifacts:
    paths:
      - aws-openebs/

cassandra-jiva:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-aws-deploy
  script: 
   #- echo "jobs-AWS-Started"
   - chmod 775 ./script/cassandra-app-deploy
   - ./script/cassandra-app-deploy

  artifacts:
    paths:
      - aws-openebs/

jenkins-jiva:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-aws-deploy
  script: 
   #- echo "jobs-AWS-Started"
   - chmod 775 ./script/jenkins-app-deploy
   - ./script/jenkins-app-deploy

  artifacts:
    paths:
      - aws-openebs/

percona-loadgen:
  image: atulabhi/kops:v8
  stage: apps-loadgen
  dependencies:
    - percona-jiva
  script:
   - chmod 755 ./script/percona-loadgen
   - ./script/percona-loadgen

  artifacts:
    paths:
      - aws-deploy

cassandra-loadgen:
  image: atulabhi/kops:v8
  stage: apps-loadgen
  dependencies:
    - cassandra-jiva
  script:
    - chmod 755 ./script/cassandra-loadgen
    - ./script/cassandra-loadgen

  artifacts:
    paths:
      - aws-deploy

mongodb-loadgen:
  image: atulabhi/kops:v8
  stage: apps-loadgen
  dependencies:
    - mongodb-jiva
  script:
    - chmod 755 ./script/mongodb-loadgen
    - ./script/mongodb-loadgen

  artifacts:
    paths:
      - aws-deploy

Litmus-Chaos:
  image: atulabhi/kops:v8
  dependencies:
    - percona-jiva
  stage: chaos-test
  script:
   - chmod 775 ./script/app-chaos
   - ./script/app-chaos

  artifacts:
    paths:
      - aws-openebs/

cleanup-aws:
  when: always
  image: atulabhi/kops:v8
  dependencies:
    - aws-cluster
  stage: cleanup
  script: 
    - chmod 755 ./script/aws-cleanup
    - ./script/aws-cleanup
