## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - CLUSTER-CLEANUP


## Setup the kubernetes cluster

aws-cluster:
  image: harshshekhar15/gitlab-job:v6
  stage: CLUSTER-SETUP 
  script: 
    - ./script/aws
  artifacts:
    paths:
      - aws/

## Deprrovision kubernets cluster

cleanup-aws:
  when: always
  image: harshshekhar15/gitlab-job:v6
  dependencies:
    - aws-cluster
  stage: CLUSTER-CLEANUP
  script: 
    - chmod 755 ./script/aws-cleanup
    - ./script/aws-cleanup
