## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - PROVIDER-INFRA-SETUP
  - APP-FUNC-TEST
  - MIGRATE-OPENEBS
  - APP-CHAOS-TEST
  - CLUSTER-CLEANUP

variables:
  utils_path: "/builds/openebs/e2e-aws/script/utils"

## Setup the kubernetes cluster

aws-cluster:
  image: harshshekhar15/gitlab-job:v6
  stage: CLUSTER-SETUP 
  script: 
    - ./script/1-cluster-setup/aws
  artifacts:
    paths:
      - aws/

## Setup OpenEBS control plane

openebs-aws-deploy:
  image: harshshekhar15/gitlab-job:v6
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - aws-cluster
  script:
   - chmod 775 ./script/2-infra-setup/openebs-deploy/infra-setup
   - ./script/2-infra-setup/openebs-deploy/infra-setup
  artifacts:
    paths:
      - aws-openebs/

openebs-sc-deploy:
  image: harshshekhar15/gitlab-job:v6
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - aws-cluster
  script:
   - chmod 775 ./script/2-infra-setup/storage-policies/openebs-sc
   - ./script/2-infra-setup/storage-policies/openebs-sc
  artifacts:
    paths:
      - aws-openebs/

cStor-striped-pool:
  image: harshshekhar15/gitlab-job:v6
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - aws-cluster
  script:
   - chmod 775 ./script/2-infra-setup/create-striped-pool/create-striped-pool
   - ./script/2-infra-setup/create-striped-pool/create-striped-pool
  artifacts:
    paths:
      - aws-openebs/

# ## Define job template for func jobs    
.func_test_template:
  image: harshshekhar15/gitlab-job:v6
  stage: APP-FUNC-TEST
  dependencies:
    - openebs-aws-deploy
  artifacts:
    paths:
     - aws-openebs/

busybox-deployment-cstor:
  extends: .func_test_template
  script:
    - chmod 775 ./script/3-functional/busybox-deployment-cstor/busybox-deployment-cstor
    - ./script/3-functional/busybox-deployment-cstor/busybox-deployment-cstor

percona-deployment-cstor:
  extends: .func_test_template
  script:
    - chmod 775 ./script/3-functional/percona-deployment-cstor/percona-deployment-cstor
    - ./script/3-functional/percona-deployment-cstor/percona-deployment-cstor

percona-deployment-localpv-device:
  extends: .func_test_template
  script:
    - chmod 775 ./script/3-functional/percona-localpv-device/percona-localpv-device
    - ./script/3-functional/percona-localpv-device/percona-localpv-device

.migrate_openebs:
  image: harshshekhar15/gitlab-job:v6
  stage: UPGRADE-OPENEBS
  dependencies:
    - openebs-aws-deploy
  artifacts:
    paths:
     - aws-openebs/

upgrade-control-plane:
  extends: .migrate_openebs
  script:
    - chmod 775 ./script/4-migrate-openebs/upgrade-control-plane
    - ./script/4-migrate-openebs/upgrade-control-plane

cstor-operator-provision:
  extends: .migrate_openebs
  script:
    - chmod 775 ./script/4-migrate-openebs/cspc-cstor-operator
    - ./script/4-migrate-openebs/cspc-cstor-operator

migrate-spc-pool:
  extends: .migrate_openebs
  script:
    - chmod 775 ./script/4-migrate-openebs/migrate-cstor-pool
    - ./script/4-migrate-openebs/migrate-cstor-pool

migrate-cstor-volume:
  extends: .migrate_openebs
  script:
    - chmod 775 ./script/4-migrate-openebs/migrate-cstor-volume
    - ./script/4-migrate-openebs/migrate-cstor-volume

.chaos_test_template:
  image: harshshekhar15/gitlab-job:v6
  stage: APP-CHAOS-TEST
  dependencies:
    - openebs-aws-deploy
  artifacts:
    paths:
     - aws-openebs/
    
busybox-deployment-target-network-delay:
  extends: .chaos_test_template
  script:
    - chmod 775 ./script/5-chaos/bb-deployment-target-nw-delay
    - ./script/5-chaos/bb-deployment-target-nw-delay

percona-target-network-delay:
  extends: .chaos_test_template
  script:
    - chmod 775 ./script/5-chaos/percona-target-nw-delay
    - ./script/5-chaos/percona-target-nw-delay

percona-cstor:
  extends: .chaos_test_template
  script:
    - chmod 775 ./script/5-chaos/percona-deployment-cstor
    - ./script/5-chaos/percona-deployment-cstor

percona-verify-data-persistence-device:
  extends: .chaos_test_template
  script:
    - chmod 775 ./script/5-chaos/percona-verify-data-persistence-device
    - ./script/5-chaos/percona-verify-data-persistence-device

percona-verify-data-persistence-hostpath:
  extends: .chaos_test_template
  script:
    - chmod 775 ./script/5-chaos/percona-verify-data-persistence-hostpath
    - ./script/5-chaos/percona-verify-data-persistence-hostpath

percona-deploy-localpv-device:
  extends: .chaos_test_template
  script:
    - chmod 775 ./script/5-chaos/percona-deployment-device
    - ./script/5-chaos/percona-deployment-device

percona-deploy-localpv-hostpath:
  extends: .chaos_test_template
  script:
    - chmod 775 ./script/5-chaos/percona-deployment-hostpath
    - ./script/5-chaos/percona-deployment-hostpath

## Deprrovision kubernets cluster

cleanup-aws:
  when: always
  image: harshshekhar15/gitlab-job:v6
  dependencies:
    - aws-cluster
  stage: CLUSTER-CLEANUP
  script: 
    - chmod 755 ./script/6-cleanup/aws-cleanup
    - ./script/6-cleanup/aws-cleanup