#!/bin/bash
set -x

job_id=$CI_JOB_ID
pipeline_id=$CI_PIPELINE_ID
commit_id=$CI_COMMIT_SHA
releaseTag=$RELEASE_TAG
release_version=$RELEASE_TAG
release_branch=$CSPC_FROM_BRANCH
source ~/.profile
gittoken=$(echo "$github_token")
csi_ns=$CSI_NAMESPACE

time="date"
current_time=$(eval $time)

echo "Setting up test dependencies.."
${utils_path}/setup_dependencies litmus-test

#pooling over previous job to complete
bash script/utils/pooling jobname:upgrade-control-plane
bash script/utils/e2e-cr jobname:cstor-operator jobphase:Waiting
bash script/utils/e2e-cr jobname:cstor-operator jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag"

test_name=$(bash script/utils/generate_test_name testcase=openebs-cstor-operator-provision metadata="")
echo $test_name

git clone https://github.com/mayadata-io/litmus.git
cd litmus

# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp providers/cstor-operator/run_litmus_test.yml cstor_operator.yml

sed -i -e "/name: IMAGE_TAG/{n;s/.*/            value: ${releaseTag}/g}" \
-e "/name: RELEASE_BRANCH/{n;s/.*/            value: ${release_branch}/g}" \
-e "/name: CSI_NS/{n;s/.*/            value: ${csi_ns}/g}" \
-e "/name: NODE_OS/{n;s/.*/            value: 'ubuntu-16.04'/g}" \
-e "/name: RELEASE_VERSION/{n;s/.*/            value: ${release_version}/g}" cstor_operator.yml

cat cstor_operator.yml

bash ../script/utils/litmus_job_runner label='provider:cstor-operator' job=cstor_operator.yml
bash ../script/utils/dump_cluster_state;
cd ..
bash script/utils/event_updater jobname:cstor-operator $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

#################
## GET RESULT  ##
#################
rc_val=$(echo $?)

## Check the test status & result from the litmus result custom resource
source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash script/utils/e2e-cr jobname:cstor-operator jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Pass

if [ "$rc_val" != "0" ]; then
exit 1;
fi
