#!/bin/bash
set -x

time="date"
current_time=$(eval $time)
job_id=$CI_JOB_ID
pipeline_id=$CI_PIPELINE_ID
to_version=$RELEASE_TAG
upgrade_imageTag=$UPGRADE_IMAGE_TAG

source ~/.profile

present_dir=$(pwd)
echo $present_dir

echo "Setting up test dependencies.."	
${utils_path}/setup_dependencies litmus-test	

bash script/utils/pooling jobname:cstor-operator
bash script/utils/e2e-cr jobname:migrate-cstor-pool jobphase:Waiting
bash script/utils/e2e-cr jobname:migrate-cstor-pool jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag"

test_name=$(bash script/utils/generate_test_name testcase=cstor-cspc-csi-migration metadata="")
echo $test_name

git clone https://github.com/mayadata-io/litmus.git
cd litmus
echo "Running the litmus test.."

cp providers/openebs/cspc_csi_migration/run_litmus_test.yml migrate-cstor-pool.yml

sed -i -e '/name: MIGRATE_SPC_POOL/{n;s/.*/            value: "true"/}' \
-e '/name: MIGRATATION_IMAGE_TAG/{n;s/.*/            value: '"'$to_version'"'/}' \
-e '/name: OPERATOR_NS/{n;s/.*/            value: openebs/}' migrate-cstor-pool.yml

cat migrate-cstor-pool.yml

bash ../script/utils/litmus_job_runner label='app:cspc-csi-migration' job=migrate-cstor-pool.yml

echo "Dumping state of cluster post job run"; echo ""
bash ../script/utils/dump_cluster_state;

cd ..
bash script/utils/event_updater jobname:migrate-cstor-pool $test_name jobid:"$job_id" pipelineid:"$pipeline_id"
#################
## GET RESULT  ##
#################
rc_val=$(echo $?)
kubectl get pods -n openebs -o yaml | grep image | grep -v imageID | grep quay

## Check the test status & result from the litmus result custom resource
source ~/.profile
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash script/utils/e2e-cr jobname:migrate-cstor-pool jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:$testResult

if [ "$rc_val" != "0" ]; then
exit 1;
fi
