#!/bin/bash
set -x

job_id=$CI_JOB_ID
pipeline_id=$CI_PIPELINE_ID
commit_id=$CI_COMMIT_SHA
release_version=$FROM_VERSION
releaseTag=$TO_VERSION
release_branch=$CSPC_FROM_BRANCH
source ~/.profile
gittoken=$(echo "$github_token")
csi_ns=$CSI_NAMESPACE
release_commit_id=$FROM_COMMIT_ID
rc_tag=$FROM_RC_TAG

time="date"
current_time=$(eval $time)

echo "Setting up test dependencies.."
${utils_path}/setup_dependencies infra-setup

kubectl apply -f script/utils/e2e-crd.yml

#pooling over previous job to complete
bash script/utils/e2e-cr jobname:cstor-operator jobphase:Waiting
bash script/utils/e2e-cr jobname:cstor-operator jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag"

test_name=$(bash script/utils/generate_test_name testcase=openebs-cstor-operator-provision metadata="")
echo $test_name

git clone https://github.com/openebs/upgrade.git
cd upgrade/e2e-tests

kubectl apply -f hack/rbac.yaml
kubectl apply -f hack/crds.yaml

# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp experiments/cstor-operator-provision/run_e2e_test.yml cstor_operator.yml

sed -i -e "/name: COMMIT_ID/{n;s/.*/            value: charts/g}" \
-e "/name: RC_TAG/{n;s/.*/            value: ${rc_tag}/g}" \
-e "/name: CSI_NS/{n;s/.*/            value: ${csi_ns}/g}" \
-e "/name: OPENEBS_VERSION/{n;s/.*/            value: ${release_version}/g}" cstor_operator.yml

cat cstor_operator.yml

bash ../../script/utils/e2e_job_runner label='provider:cstor-operator' job=cstor_operator.yml
bash ../../script/utils/dump_cluster_state;
cd ../..
bash script/utils/event_updater jobname:cstor-operator $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

#################
## GET RESULT  ##
#################
rc_val=$(echo $?)

## Check the test status & result from the e2e result custom resource
source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get e2eresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash script/utils/e2e-cr jobname:cstor-operator jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Pass

if [ "$rc_val" != "0" ]; then
exit 1;
fi
