#!/bin/bash
set -e
path=$(pwd)
# ----------------------------- Creating directory ---------------------
mkdir ~/.aws $path/aws $path/aws/cluster $path/aws/ssh $path/aws/.kube $path/cluster && cd $path/cluster

# ----------------------------- Setting AWS credentials ----------------
echo $CONFIG > ~/.aws/config
echo $CREDENTIALS > ~/.aws/credentials
export AWS_ACCESS_KEY_ID=$AC_ID
export AWS_SECRET_ACCESS_KEY=$AC_KEY
export AWS_DEFAULT_REGION=eu-west-2
export AWS_DEFAULT_OUTPUT=json

# ----------------------------- Cloning litmus repository --------------
git clone https://github.com/openebs/litmus.git
#git clone https://github.com/chandankumar4/litmus.git
cd litmus/k8s/aws/k8s-installer

# ------- Creating Pre-requisite for setup AWS cluster -----------------
echo "creating pre-requisite"
ansible-playbook pre-requisite.yml -v

# ----------------------------- Creating AWS Cluster -------------------
echo "creating  AWS cluster"

## Note: Default taints from https://github.com/openebs/litmus/blob/master/k8s/aws/k8s-installer/create-aws-cluster.yml#L70
ansible-playbook create-aws-cluster.yml --extra-vars "k8s_version=1.10.0 node_count=4 taint_value=infra-aid=observer:NoSchedule" -v

# ------------------- Applying rbac.yml of litmus ---------------------
wget https://raw.githubusercontent.com/openebs/litmus/master/hack/rbac.yaml
kubectl apply -f rbac.yaml

# --------------------- Preparing for gitlab artifact ------------------
cat /tmp/aws/cluster_name.csv > $path/aws/cluster/cluster_name.csv
cat /tmp/aws/id.csv > $path/aws/cluster/id.csv
cat /tmp/aws/node_property > $path/aws/cluster/node_property
# mkdir /openebs/e2e-aws/aws/.kube
cat ~/.kube/config > $path/aws/.kube/admin.conf
cat ~/.kube/config > $path/aws/.kube/config
cp -r ~/.ssh/. $path/aws/ssh

# -------------------------- Applying configmap -------------------------
kubectl create configmap kubeconfig --from-file=$path/aws/.kube/admin.conf -n litmus

# -------------------------- Attach Disks -------------------------------
aws_cluster_name=$(cat /tmp/aws/cluster_name.csv | cut -d ":" -f 2); echo ${aws_cluster_name}
cd ../ebs-volumes
ansible-playbook create-ebs-volume.yml --extra-vars "cluster_name=nodes.k8s-${aws_cluster_name}.k8s.local" -vv
cat /tmp/aws/volume-id > $path/aws/cluster/volume-id
cat /tmp/aws/volume-id
