#!/bin/bash
set -e

path=$(pwd)
# ----------------------------- Creating directory ---------------------
mkdir ~/.aws $path/aws $path/aws/cluster $path/aws/ssh $path/cluster && cd $path/cluster

# ----------------------------- Setting AWS credentials ----------------
export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
export AWS_DEFAULT_REGION=eu-central-1
export AWS_DEFAULT_OUTPUT=json

aws configure set aws_access_key_id $AWS_ACCESS_KEY
aws configure set aws_secret_access_key $AWS_SECRET_KEY

# ----------------------------- Cloning litmus repository --------------
git clone https://github.com/openebs/e2e-tests.git
cd e2e-tests/k8s/aws/k8s-installer

# ------- Creating Pre-requisite for setup AWS cluster -----------------
echo "creating pre-requisite"

sed -i -e 's/region: eu-west-2/region: eu-central-1/g' \
-e 's/image: ami-6b3fd60c/image: ami-03d8059563982d7b0/g' \
-e 's/zone: eu-west-2a/zone: eu-central-1a/g' vars.yml

ansible-playbook pre-requisite.yml -v

# ----------------------------- Creating AWS Cluster -------------------
sed -i -e 's/region: eu-west-2/region: eu-central-1/g' \
-e 's/zone: eu-west-2a/zone: eu-central-1a/g' vars.yml
echo "creating  AWS cluster"
ansible-playbook create-aws-cluster.yml --extra-vars "k8s_version=1.16.9" -v

# ------------------- Applying rbac.yml of litmus ---------------------
wget https://raw.githubusercontent.com/openebs/e2e-tests/master/hack/rbac.yaml
kubectl apply -f rbac.yaml
wget https://raw.githubusercontent.com/openebs/e2e-tests/master/hack/crds.yaml
kubectl apply -f crds.yaml
# --------------------- Preparing for gitlab artifact ------------------
cat /tmp/aws/cluster_name.csv > $path/aws/cluster/cluster_name.csv
cat /tmp/aws/id.csv > $path/aws/cluster/id.csv
mkdir $path/aws/.kube
cat ~/.kube/config > $path/aws/.kube/admin.conf
cat ~/.kube/config > $path/aws/.kube/config
cp -r ~/.ssh/. $path/aws/ssh

# -------------------------- Applying configmap -------------------------
kubectl create configmap kubeconfig --from-file=$path/aws/.kube/admin.conf -n litmus

# -------------------------- Attach Disks -------------------------------
aws_cluster_name=$(cat /tmp/aws/cluster_name.csv | cut -d ":" -f 2); echo ${aws_cluster_name}
cd ../ebs-volumes
ansible-playbook create-ebs-volume.yml --extra-vars "cluster_name=nodes.k8s-${aws_cluster_name}.k8s.local" -vv
cat /tmp/aws/volume-id > $path/aws/cluster/volume-id
cat /tmp/aws/volume-id
