#!/bin/bash

set -e

echo "AWS Cluster Cleaning"

# ------------------------- Setting AWS credentails -------------------------------

export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
export AWS_DEFAULT_REGION=eu-central-1
export AWS_DEFAULT_OUTPUT=json

aws configure set aws_access_key_id $AWS_ACCESS_KEY
aws configure set aws_secret_access_key $AWS_SECRET_KEY

path=$(pwd)

# ---- Creating Directory and storing necessary data inside it --------------------
cat $path/aws/cluster/id.csv > /tmp/aws/id.csv
cat $path/aws/cluster/cluster_name.csv > /tmp/aws/cluster_name.csv
cat $path/aws/cluster/volume-id > /tmp/aws/volume-id

aws_cluster_name=$(cat /tmp/aws/cluster_name.csv | cut -d ":" -f 2); echo ${aws_cluster_name}

# ---- Cloning e2e repository for cleaning AWS cluster and pre-requisite--------
git clone https://github.com/openebs/e2e-tests.git
cd  e2e-tests/k8s/aws/k8s-installer

# ---------------------- Deleting AWS cluster -------------------------------------
sed -i -e 's/region: eu-west-2/region: eu-central-1/g' \
-e 's/zone: eu-west-2a/zone: eu-central-1a/g' vars.yml
ansible-playbook delete-aws-cluster.yml -v

# ---------------------- Deleting AWS pre-requisite -------------------------------
ansible-playbook delete-pre-requisite.yml -v

# ---------------------- Deleting Disks ------------------------------------------#
cd ../ebs-volumes
sed -i -e 's/region: eu-west-2/region: eu-central-1/g' \
-e 's/volume_size: 50/volume_size: 25/g' \
-e 's/zone: eu-west-2a/zone: eu-central-1a/g' vars.yml
ansible-playbook delete-ebs-volume.yml --extra-vars "cluster_name=nodes.k8s-${aws_cluster_name}.k8s.local"
